sudo: false
language: scala
scala:
  - 2.12.8
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test
jdk:
  - oraclejdk8
notifications:
  slack:
    secure: hyO/hJtqqoR7qR8AhwSpivpsU45u+Bnj+y4jN7fy58NtnSyrJmplWQHX2cXBtlf4mZlb1GsPjvQViqqbtuio9w6nUJqtbyotsjDtmtuAsaqrITLcSchMYUVFCw+pY8pFquPZgLkuUrcbK93R9PHpZOAXbkhkpSI+2oGPDnprifbzwiXGxoPP2fknUNSkGUSpwtmeiB2brISCN/Vpbh1eAY4yUm/l8A+sFJpuaYLAgcQ5uyo13Ud1B9G9Ub3W61CZo46b4cYEA6IkKaDwBt1t8QPw0u1N3oNerQbbdFFBe0FUxkGUsz6bgt8zh0n3+UQ78Ot2qX7HR+bzFk09LaSbZhguVaA87BINZ5undlNk3RuK0wBha73LXVAU1yoU0FvERvFEByHbhWOko9/6rgdCtoGk9C/ffSZ/2Sh1DxLyNNRJ4TpfFgHxe1W7ViiF04hzb4FDj13ecqfdQeqaFquAS2lvin9VOQK61Fv5/0Gu0LGVcLHVkWnhAWfCGyW1hloUjxDSEPvn4knXFYuORnQ0PFhQr41mkRCbf4jFWQdvfmoYR2JAvN7ktjz+x+6gW0W07PKh1ONqV6xzbMODA1+noIOY13C2vHP8MxpKpOTcGG3W+etP0CN83LV96XSdLCF2tBL0b0v1EKXQlFpFU6gW1lcVpIE8c/nQ/7pfIrpsArk=