package com.cyclone.ipmi.protocol.jedec

object Bank07 extends Manufacturer.Bank {

  protected lazy val names: Map[Byte, String] = Map(
    0x01.toByte -> "MOVEKING",
    0x02.toByte -> "Mavrix Technology, Inc.",
    0x83.toByte -> "CellGuide Ltd.",
    0x04.toByte -> "Faraday Technology",
    0x85.toByte -> "Diablo Technologies, Inc.",
    0x86.toByte -> "Jennic",
    0x07.toByte -> "Octasic",
    0x08.toByte -> "Molex Incorporated",
    0x89.toByte -> "3Leaf Networks",
    0x8A.toByte -> "Bright Micron Technology",
    0x0B.toByte -> "Netxen",
    0x8C.toByte -> "NextWave Broadband Inc.",
    0x0D.toByte -> "DisplayLink",
    0x0E.toByte -> "ZMOS Technology",
    0x8F.toByte -> "Tec-Hill",
    0x10.toByte -> "Multigig, Inc.",
    0x91.toByte -> "Amimon",
    0x92.toByte -> "Euphonic Technologies, Inc.",
    0x13.toByte -> "BRN Phoenix",
    0x94.toByte -> "InSilica",
    0x15.toByte -> "Ember Corporation",
    0x16.toByte -> "Avexir Technologies Corporation",
    0x97.toByte -> "Echelon Corporation",
    0x98.toByte -> "Edgewater Computer Systems",
    0x19.toByte -> "XMOS Semiconductor Ltd.",
    0x1A.toByte -> "GENUSION, Inc.",
    0x9B.toByte -> "Memory Corp NV",
    0x1C.toByte -> "SiliconBlue Technologies",
    0x9D.toByte -> "Rambus Inc.",
    0x9E.toByte -> "Andes Technology Corporation",
    0x1F.toByte -> "Coronis Systems",
    0x20.toByte -> "Achronix Semiconductor",
    0xA1.toByte -> "Siano Mobile Silicon Ltd.",
    0xA2.toByte -> "Semtech Corporation",
    0x23.toByte -> "Pixelworks Inc.",
    0xA4.toByte -> "Gaisler Research AB",
    0x25.toByte -> "Teranetics",
    0x26.toByte -> "Toppan Printing Co. Ltd.",
    0xA7.toByte -> "Kingxcon",
    0xA8.toByte -> "Silicon Integrated Systems",
    0x29.toByte -> "I-O Data Device, Inc.",
    0x2A.toByte -> "NDS Americas Inc.",
    0xAB.toByte -> "Solomon Systech Limited",
    0x2C.toByte -> "On Demand Microelectronics",
    0xAD.toByte -> "Amicus Wireless Inc.",
    0xAE.toByte -> "SMARDTV SNC",
    0x2F.toByte -> "Comsys Communication Ltd.",
    0xB0.toByte -> "Movidia Ltd.",
    0x31.toByte -> "Javad GNSS, Inc.",
    0x32.toByte -> "Montage Technology Group",
    0xB3.toByte -> "Trident Microsystems",
    0x34.toByte -> "Super Talent",
    0xB5.toByte -> "Optichron, Inc.",
    0xB6.toByte -> "Future Waves UK Ltd.",
    0x37.toByte -> "SiBEAM, Inc.",
    0x38.toByte -> "Inicore,Inc.",
    0xB9.toByte -> "Virident Systems",
    0xBA.toByte -> "M2000, Inc.",
    0x3B.toByte -> "ZeroG Wireless, Inc.",
    0xBC.toByte -> "Gingle Technology Co. Ltd.",
    0x3D.toByte -> "Space Micro Inc.",
    0x3E.toByte -> "Wilocity",
    0xBF.toByte -> "Novafora, Inc.",
    0x40.toByte -> "iKoa Corporation",
    0xC1.toByte -> "ASint Technology",
    0xC2.toByte -> "Ramtron",
    0x43.toByte -> "Plato Networks Inc.",
    0xC4.toByte -> "IPtronics AS",
    0x45.toByte -> "Infinite-Memories",
    0x46.toByte -> "Parade Technologies Inc.",
    0xC7.toByte -> "Dune Networks",
    0xC8.toByte -> "GigaDevice Semiconductor",
    0x49.toByte -> "Modu Ltd.",
    0x4A.toByte -> "CEITEC",
    0xCB.toByte -> "Northrop Grumman",
    0x4C.toByte -> "XRONET Corporation",
    0xCD.toByte -> "Sicon Semiconductor AB",
    0xCE.toByte -> "Atla Electronics Co. Ltd.",
    0x4F.toByte -> "TOPRAM Technology",
    0xD0.toByte -> "Silego Technology Inc.",
    0x51.toByte -> "Kinglife",
    0x52.toByte -> "Ability Industries Ltd.",
    0xD3.toByte -> "Silicon Power Computer & Communications",
    0x54.toByte -> "Augusta Technology, Inc.",
    0xD5.toByte -> "Nantronics Semiconductors",
    0xD6.toByte -> "Hilscher Gesellschaft",
    0x57.toByte -> "Quixant Ltd.",
    0x58.toByte -> "Percello Ltd.",
    0xD9.toByte -> "NextIO Inc.",
    0xDA.toByte -> "Scanimetrics Inc.",
    0x5B.toByte -> "FS-Semi Company Ltd.",
    0xDC.toByte -> "Infinera Corporation",
    0x5D.toByte -> "SandForce Inc.",
    0x5E.toByte -> "Lexar Media",
    0xDF.toByte -> "Teradyne Inc.",
    0xE0.toByte -> "Memory Exchange Corp.",
    0x61.toByte -> "Suzhou Smartek Electronics",
    0x62.toByte -> "Avantium Corporation",
    0xE3.toByte -> "ATP Electronics Inc.",
    0x64.toByte -> "Valens Semiconductor Ltd",
    0xE5.toByte -> "Agate Logic, Inc.",
    0xE6.toByte -> "Netronome",
    0x67.toByte -> "Zenverge, Inc.",
    0x68.toByte -> "N-trig Ltd",
    0xE9.toByte -> "SanMax Technologies Inc.",
    0xEA.toByte -> "Contour Semiconductor Inc.",
    0x6B.toByte -> "TwinMOS",
    0xEC.toByte -> "Silicon Systems, Inc.",
    0x6D.toByte -> "V-Color Technology Inc.",
    0x6E.toByte -> "Certicom Corporation",
    0xEF.toByte -> "JSC ICC Milandr",
    0x70.toByte -> "PhotoFast Global Inc.",
    0xF1.toByte -> "InnoDisk Corporation",
    0xF2.toByte -> "Muscle Power",
    0x73.toByte -> "Energy Micro",
    0xF4.toByte -> "Innofidei",
    0x75.toByte -> "CopperGate Communications",
    0x76.toByte -> "Holtek Semiconductor Inc.",
    0xF7.toByte -> "Myson Century, Inc.",
    0xF8.toByte -> "FIDELIX",
    0x79.toByte -> "Red Digital Cinema",
    0x7A.toByte -> "Densbits Technology",
    0xFB.toByte -> "Zempro",
    0x7C.toByte -> "MoSys",
    0xFD.toByte -> "Provigent",
    0xFE.toByte -> "Triad Semiconductor, Inc."
  )
}
