package com.cyclone.ipmi.protocol.jedec

object Bank09 extends Manufacturer.Bank {

  protected lazy val names: Map[Byte, String] = Map(
    0x01.toByte -> "3D PLUS",
    0x02.toByte -> "Diehl Aerospace",
    0x83.toByte -> "Fairchild",
    0x04.toByte -> "Mercury Systems",
    0x85.toByte -> "Sonics, Inc.",
    0x86.toByte -> "GE Intelligent Platforms GmbH & Co.",
    0x07.toByte -> "Shenzhen Jinge Information Co. Ltd.",
    0x08.toByte -> "SCWW",
    0x89.toByte -> "Silicon Motion Inc.",
    0x8A.toByte -> "Anurag",
    0x0B.toByte -> "King Kong",
    0x8C.toByte -> "FROM30 Co. Ltd.",
    0x0D.toByte -> "Gowin Semiconductor Corp",
    0x0E.toByte -> "Fremont Micro Devices Ltd.",
    0x8F.toByte -> "Ericsson Modems",
    0x10.toByte -> "Exelis",
    0x91.toByte -> "Satixfy Ltd.",
    0x92.toByte -> "Galaxy Microsystems Ltd.",
    0x13.toByte -> "Gloway International Co. Ltd.",
    0x94.toByte -> "Lab",
    0x15.toByte -> "Smart Energy Instruments",
    0x16.toByte -> "Approved Memory Corporation",
    0x97.toByte -> "Axell Corporation",
    0x98.toByte -> "Essencore Limited",
    0x19.toByte -> "Phytium",
    0x1A.toByte -> "Xi’an SinoChip Semiconductor",
    0x9B.toByte -> "Ambiq Micro",
    0x1C.toByte -> "eveRAM Technology, Inc.",
    0x9D.toByte -> "Infomax",
    0x9E.toByte -> "Butterfly Network, Inc.",
    0x1F.toByte -> "Shenzhen City Gcai Electronics",
    0x20.toByte -> "Stack Devices Corporation",
    0xA1.toByte -> "",
    0xA2.toByte -> "TSP Global Co., Ltd.",
    0x23.toByte -> "HighX",
    0xA4.toByte -> "Shenzhen Elicks Technology",
    0x25.toByte -> "ISSI/Chingis",
    0x26.toByte -> "Google, Inc.",
    0xA7.toByte -> "Dasima International Development",
    0xA8.toByte -> "Leahkinn Technology Limited",
    0x29.toByte -> "HIMA Paul Hildebrandt GmbH Co KG",
    0x2A.toByte -> "Keysight Technologies",
    0xAB.toByte -> "Techcomp International (Fastable)",
    0x2C.toByte -> "Ancore Technology Corporation",
    0xAD.toByte -> "Nuvoton",
    0xAE.toByte -> "Korea Uhbele International Group Ltd.",
    0x2F.toByte -> "Ikegami Tsushinki Co Ltd.",
    0xB0.toByte -> "RelChip, Inc.",
    0x31.toByte -> "Baikal Electronics",
    0x32.toByte -> "Nemostech Inc.",
    0xB3.toByte -> "Memorysolution GmbH",
    0x34.toByte -> "Silicon Integrated Systems Corporation",
    0xB5.toByte -> "Xiede",
    0xB6.toByte -> "Multilaser Components",
    0x37.toByte -> "Flash Chi",
    0x38.toByte -> "Jone",
    0xB9.toByte -> "GCT Semiconductor Inc.",
    0xBA.toByte -> "Hong Kong Zetta Device Technology",
    0x3B.toByte -> "Unimemory Technology(s) Pte Ltd.",
    0xBC.toByte -> "Cuso",
    0x3D.toByte -> "Kuso",
    0x3E.toByte -> "Uniquify Inc.",
    0xBF.toByte -> "Skymedi Corporation",
    0x40.toByte -> "Core Chance Co. Ltd.",
    0xC1.toByte -> "Tekism Co. Ltd.",
    0xC2.toByte -> "Seagate Technology PLC",
    0x43.toByte -> "Hong Kong Gaia Group Co. Limited",
    0xC4.toByte -> "Gigacom Semiconductor LLC",
    0x45.toByte -> "V2 Technologies",
    0x46.toByte -> "TLi",
    0xC7.toByte -> "Neotion",
    0xC8.toByte -> "Lenovo",
    0x49.toByte -> "Shenzhen Zhongteng Electronic Corp. Ltd.",
    0x4A.toByte -> "Compound Photonics",
    0xCB.toByte -> "in2H2 inc",
    0x4C.toByte -> "Shenzhen Pango Microsystems Co. Ltd",
    0xCD.toByte -> "Vasekey",
    0xCE.toByte -> "Cal-Comp Industria de Semicondutores",
    0x4F.toByte -> "Eyenix Co., Ltd.",
    0xD0.toByte -> "Heoriady",
    0x51.toByte -> "Accelerated Memory Production Inc.",
    0x52.toByte -> "INVECAS, Inc.",
    0xD3.toByte -> "AP Memory",
    0x54.toByte -> "Douqi Technology",
    0xD5.toByte -> "Etron Technology, Inc.",
    0xD6.toByte -> "Indie Semiconductor",
    0x57.toByte -> "Socionext Inc.",
    0x58.toByte -> "HGST",
    0xD9.toByte -> "EVGA",
    0xDA.toByte -> "Audience Inc.",
    0x5B.toByte -> "EpicGear",
    0xDC.toByte -> "Vitesse Enterprise Co.",
    0x5D.toByte -> "Foxtronn International Corporation",
    0x5E.toByte -> "Bretelon Inc.",
    0xDF.toByte -> "Graphcore",
    0xE0.toByte -> "Eoplex Inc",
    0x61.toByte -> "MaxLinear, Inc.",
    0x62.toByte -> "ETA Devices",
    0xE3.toByte -> "LOKI",
    0x64.toByte -> "IMS Electronics Co., Ltd.",
    0xE5.toByte -> "Dosilicon Co., Ltd.",
    0xE6.toByte -> "Dolphin Integration",
    0x67.toByte -> "Shenzhen Mic Electronics Technology",
    0x68.toByte -> "Boya Microelectronics Inc.",
    0xE9.toByte -> "Geniachip (Roche)",
    0xEA.toByte -> "Axign",
    0x6B.toByte -> "Kingred Electronic Technology Ltd.",
    0xEC.toByte -> "Chao Yue Zhuo Computer Business Dept.",
    0x6D.toByte -> "Guangzhou Si Nuo Electronic Technology.",
    0x6E.toByte -> "",
    0xEF.toByte -> "Creative Chips GmbH",
    0x70.toByte -> "GE Aviation Systems LLC.",
    0xF1.toByte -> "Asgard",
    0xF2.toByte -> "Good Wealth Technology Ltd.",
    0x73.toByte -> "TriCor Technologies",
    0xF4.toByte -> "Nova-Systems GmbH",
    0x75.toByte -> "JUHOR",
    0x76.toByte -> "Zhuhai Douke Commerce Co. Ltd.",
    0xF7.toByte -> "DSL Memory",
    0xF8.toByte -> "Anvo-Systems Dresden GmbH",
    0x79.toByte -> "Realtek",
    0x7A.toByte -> "AltoBeam",
    0xFB.toByte -> "Wave Computing",
    0x7C.toByte -> "Beijing TrustNet Technology Co. Ltd.",
    0xFD.toByte -> "Innovium, Inc.",
    0xFE.toByte -> "Starsway Technology Limited"
  )
}
