package com.cyclone.ipmi.sdr.jedec

// JEDEC Manufacturer lookup
// See STANDARD MANUFACTURERS IDENTIFICATION CODE at https://www.jedec.org/
// This code is based on document JEP106AT published Spe 2016

object Bank01 extends Manufacturer.Bank {

  protected lazy val names: Map[Byte, String] = Map(
    0x01.toByte -> "AMD",
    0x02.toByte -> "AMI",
    0x83.toByte -> "Fairchild",
    0x04.toByte -> "Fujitsu",
    0x85.toByte -> "GTE",
    0x86.toByte -> "Harris",
    0x07.toByte -> "Hitachi",
    0x08.toByte -> "Inmos",
    0x89.toByte -> "Intel",
    0x8A.toByte -> "I.T.T.",
    0x0B.toByte -> "Intersil",
    0x8C.toByte -> "Monolithic Memories",
    0x0D.toByte -> "Mostek",
    0x0E.toByte -> "Freescale (Motorola)",
    0x8F.toByte -> "National",
    0x10.toByte -> "NEC",
    0x91.toByte -> "RCA",
    0x92.toByte -> "Raytheon",
    0x13.toByte -> "Conexant (Rockwell)",
    0x94.toByte -> "Seeq",
    0x15.toByte -> "NXP (Philips)",
    0x16.toByte -> "Synertek",
    0x97.toByte -> "Texas Instruments",
    0x98.toByte -> "Toshiba",
    0x19.toByte -> "Xicor",
    0x1A.toByte -> "Zilog",
    0x9B.toByte -> "Eurotechnique",
    0x1C.toByte -> "Mitsubishi",
    0x9D.toByte -> "Lucent (AT&T)",
    0x9E.toByte -> "Exel",
    0x1F.toByte -> "Atmel",
    0x20.toByte -> "STMicroelectronics",
    0xA1.toByte -> "Lattice Semi.",
    0xA2.toByte -> "NCR",
    0x23.toByte -> "Wafer Scale Integration",
    0xA4.toByte -> "IBM",
    0x25.toByte -> "Tristar",
    0x26.toByte -> "Visic",
    0xA7.toByte -> "Intl. CMOS Technology",
    0xA8.toByte -> "SSSI",
    0x29.toByte -> "MicrochipTechnology",
    0x2A.toByte -> "Ricoh Ltd.",
    0xAB.toByte -> "VLSI",
    0x2C.toByte -> "Micron Technology",
    0xAD.toByte -> "SK Hynix",
    0xAE.toByte -> "OKI Semiconductor",
    0x2F.toByte -> "ACTEL",
    0xB0.toByte -> "Sharp",
    0x31.toByte -> "Catalyst",
    0x32.toByte -> "Panasonic",
    0xB3.toByte -> "IDT",
    0x34.toByte -> "Cypress",
    0xB5.toByte -> "DEC",
    0xB6.toByte -> "LSI Logic",
    0x37.toByte -> "Zarlink (Plessey)",
    0x38.toByte -> "UTMC",
    0xB9.toByte -> "Thinking Machine",
    0xBA.toByte -> "Thomson CSF",
    0x3B.toByte -> "Integrated CMOS (Vertex)",
    0xBC.toByte -> "Honeywell",
    0x3D.toByte -> "Tektronix",
    0x3E.toByte -> "Oracle Corporation",
    0xBF.toByte -> "Silicon Storage Technology",
    0x40.toByte -> "ProMos/Mosel Vitelic",
    0xC1.toByte -> "Infineon (Siemens)",
    0xC2.toByte -> "Macronix",
    0x43.toByte -> "Xerox",
    0xC4.toByte -> "Plus Logic",
    0x45.toByte -> "SanDisk Corporation",
    0x46.toByte -> "Elan Circuit Tech.",
    0xC7.toByte -> "European Silicon Str.",
    0xC8.toByte -> "Apple Computer",
    0x49.toByte -> "Xilinx",
    0x4A.toByte -> "Compaq",
    0xCB.toByte -> "Protocol Engines",
    0x4C.toByte -> "SCI",
    0xCD.toByte -> "Seiko Instruments",
    0xCE.toByte -> "Samsung",
    0x4F.toByte -> "I3 Design System",
    0xD0.toByte -> "Klic",
    0x51.toByte -> "Crosspoint Solutions",
    0x52.toByte -> "Alliance Semiconductor",
    0xD3.toByte -> "Tandem",
    0x54.toByte -> "Hewlett-Packard",
    0xD5.toByte -> "Integrated Silicon Solutions",
    0xD6.toByte -> "Brooktree",
    0x57.toByte -> "New Media",
    0x58.toByte -> "MHS Electronic",
    0xD9.toByte -> "Performance Semi.",
    0xDA.toByte -> "Winbond Electronic",
    0x5B.toByte -> "Kawasaki Steel",
    0xDC.toByte -> "Bright Micro",
    0x5D.toByte -> "TECMAR",
    0x5E.toByte -> "Exar",
    0xDF.toByte -> "PCMCIA",
    0xE0.toByte -> "LG Semi (Goldstar)",
    0x61.toByte -> "Northern Telecom",
    0x62.toByte -> "Sanyo",
    0xE3.toByte -> "Array Microsystems",
    0x64.toByte -> "Crystal Semiconductor",
    0xE5.toByte -> "Analog Devices",
    0xE6.toByte -> "PMC-Sierra",
    0x67.toByte -> "Asparix",
    0x68.toByte -> "Convex Computer",
    0xE9.toByte -> "Quality Semiconductor",
    0xEA.toByte -> "Nimbus Technology",
    0x6B.toByte -> "Transwitch",
    0xEC.toByte -> "Micronas (ITT Intermetall)",
    0x6D.toByte -> "Cannon",
    0x6E.toByte -> "Altera",
    0xEF.toByte -> "NEXCOM",
    0x70.toByte -> "Qualcomm",
    0xF1.toByte -> "Sony",
    0xF2.toByte -> "Cray Research",
    0x73.toByte -> "AMS(Austria Micro)",
    0xF4.toByte -> "Vitesse",
    0x75.toByte -> "Aster Electronics",
    0x76.toByte -> "Bay Networks (Synoptic)",
    0xF7.toByte -> "Zentrum/ZMD",
    0xF8.toByte -> "TRW",
    0x79.toByte -> "Thesys",
    0x7A.toByte -> "Solbourne Computer",
    0xFB.toByte -> "Allied-Signal",
    0x7C.toByte -> "Dialog Semiconductor",
    0xFD.toByte -> "Media Vision",
    0xFE.toByte -> "Numonyx Corporation"
  )
}
