package com.cyclone.ipmi.sdr.jedec

// JEDEC Manufacturer lookup
// See STANDARD MANUFACTURERS IDENTIFICATION CODE at https://www.jedec.org/
// This code is based on document JEP106AT published Spe 2016

object Bank08 extends Manufacturer.Bank {

  protected lazy val names: Map[Byte, String] = Map(
    0x01.toByte -> "Siklu Communication Ltd.",
    0x02.toByte -> "A Force Manufacturing Ltd.",
    0x83.toByte -> "Strontium",
    0x04.toByte -> "ALi Corp (Abilis Systems)",
    0x85.toByte -> "Siglead, Inc.",
    0x86.toByte -> "Ubicom, Inc.",
    0x07.toByte -> "Unifosa Corporation",
    0x08.toByte -> "Stretch, Inc.",
    0x89.toByte -> "Lantiq Deutschland GmbH",
    0x8A.toByte -> "Visipro.",
    0x0B.toByte -> "EKMemory",
    0x8C.toByte -> "Microelectronics Institute ZTE",
    0x0D.toByte -> "u-blox AG",
    0x0E.toByte -> "Carry Technology Co. Ltd.",
    0x8F.toByte -> "Nokia",
    0x10.toByte -> "King Tiger Technology",
    0x91.toByte -> "Sierra Wireless",
    0x92.toByte -> "HT Micron",
    0x13.toByte -> "Albatron Technology Co. Ltd.",
    0x94.toByte -> "Leica Geosystems AG",
    0x15.toByte -> "BroadLight",
    0x16.toByte -> "AEXEA",
    0x97.toByte -> "ClariPhy Communications, Inc.",
    0x98.toByte -> "Green Plug",
    0x19.toByte -> "Design Art Networks",
    0x1A.toByte -> "Mach Xtreme Technology Ltd.",
    0x9B.toByte -> "ATO Solutions Co. Ltd.",
    0x1C.toByte -> "Ramsta",
    0x9D.toByte -> "Greenliant Systems, Ltd.",
    0x9E.toByte -> "Teikon",
    0x1F.toByte -> "Antec Hadron",
    0x20.toByte -> "NavCom Technology, Inc.",
    0xA1.toByte -> "Shanghai Fudan Microelectronics",
    0xA2.toByte -> "Calxeda, Inc.",
    0x23.toByte -> "JSC EDC Electronics",
    0xA4.toByte -> "Kandit Technology Co. Ltd.",
    0x25.toByte -> "Ramos Technology",
    0x26.toByte -> "Goldenmars Technology",
    0xA7.toByte -> "XeL Technology Inc.",
    0xA8.toByte -> "Newzone Corporation",
    0x29.toByte -> "ShenZhen MercyPower Tech",
    0x2A.toByte -> "Nanjing Yihuo Technology",
    0xAB.toByte -> "Nethra Imaging Inc.",
    0x2C.toByte -> "SiTel Semiconductor BV",
    0xAD.toByte -> "SolidGear Corporation",
    0xAE.toByte -> "Topower Computer Ind Co Ltd.",
    0x2F.toByte -> "Wilocity",
    0xB0.toByte -> "Profichip GmbH",
    0x31.toByte -> "Gerad Technologies",
    0x32.toByte -> "Ritek Corporation",
    0xB3.toByte -> "Gomos Technology Limited",
    0x34.toByte -> "Memoright Corporation",
    0xB5.toByte -> "D-Broad, Inc.",
    0xB6.toByte -> "HiSilicon Technologies",
    0x37.toByte -> "Syndiant Inc.",
    0x38.toByte -> "Enverv Inc.",
    0xB9.toByte -> "Cognex",
    0xBA.toByte -> "Xinnova Technology Inc.",
    0x3B.toByte -> "Ultron AG",
    0xBC.toByte -> "Concord Idea Corporation",
    0x3D.toByte -> "AIM Corporation",
    0x3E.toByte -> "Lifetime Memory Products",
    0xBF.toByte -> "Ramsway",
    0x40.toByte -> "Recore Systems B.V.",
    0xC1.toByte -> "Haotian Jinshibo Science Tech",
    0xC2.toByte -> "Being Advanced Memory",
    0x43.toByte -> "Adesto Technologies",
    0xC4.toByte -> "Giantec Semiconductor, Inc.",
    0x45.toByte -> "HMD Electronics AG",
    0x46.toByte -> "Gloway International (HK)",
    0xC7.toByte -> "Kingcore",
    0xC8.toByte -> "Anucell Technology Holding",
    0x49.toByte -> "Accord Software & Systems Pvt. Ltd.",
    0x4A.toByte -> "Active-Semi Inc.",
    0xCB.toByte -> "Denso Corporation",
    0x4C.toByte -> "TLSI Inc.",
    0xCD.toByte -> "Qidan",
    0xCE.toByte -> "Mustang",
    0x4F.toByte -> "Orca Systems",
    0xD0.toByte -> "Passif Semiconductor",
    0x51.toByte -> "GigaDevice Semiconductor (Beijing) Inc.",
    0x52.toByte -> "Memphis Electronic",
    0xD3.toByte -> "Beckhoff Automation GmbH",
    0x54.toByte -> "Harmony Semiconductor Corp",
    0xD5.toByte -> "Air Computers SRL",
    0xD6.toByte -> "TMT Memory",
    0x57.toByte -> "Eorex Corporation",
    0x58.toByte -> "Xingtera",
    0xD9.toByte -> "Netsol",
    0xDA.toByte -> "Bestdon Technology Co. Ltd.",
    0x5B.toByte -> "Baysand Inc.",
    0xDC.toByte -> "Uroad Technology Co. Ltd.",
    0x5D.toByte -> "Wilk Elektronik S.A.",
    0x5E.toByte -> "AAI",
    0xDF.toByte -> "Harman",
    0xE0.toByte -> "Berg Microelectronics Inc.",
    0x61.toByte -> "ASSIA, Inc.",
    0x62.toByte -> "Visiontek Products LLC",
    0xE3.toByte -> "OCMEMORY",
    0x64.toByte -> "Welink Solution Inc.",
    0xE5.toByte -> "Shark Gaming",
    0xE6.toByte -> "Avalanche Technology",
    0x67.toByte -> "R&D Center ELVEES OJSC",
    0x68.toByte -> "KingboMars Technology Co. Ltd.",
    0xE9.toByte -> "High Bridge Solutions Industria Electronica",
    0xEA.toByte -> "Transcend Technology Co. Ltd.",
    0x6B.toByte -> "Everspin Technologies",
    0xEC.toByte -> "Hon-Hai Precision",
    0x6D.toByte -> "Smart Storage Systems",
    0x6E.toByte -> "Toumaz Group",
    0xEF.toByte -> "Zentel Electronics Corporation",
    0x70.toByte -> "Panram International Corporation",
    0xF1.toByte -> "Silicon Space Technology",
    0xF2.toByte -> "LITE-ON IT Corporation",
    0x73.toByte -> "Inuitive",
    0xF4.toByte -> "HMicro",
    0x75.toByte -> "BittWare, Inc.",
    0x76.toByte -> "GLOBALFOUNDRIES",
    0xF7.toByte -> "ACPI Digital Co. Ltd.",
    0xF8.toByte -> "Annapurna Labs",
    0x79.toByte -> "AcSiP Technology Corporation",
    0x7A.toByte -> "Idea! Electronic Systems",
    0xFB.toByte -> "Gowe Technology Co. Ltd.",
    0x7C.toByte -> "Hermes Testing Solutions, Inc.",
    0xFD.toByte -> "Positivo BGH",
    0xFE.toByte -> "Intelligence  Silicon Technology"
  )
}
