package com.cyclone.ipmi.sdr.jedec

object Bank04 extends Manufacturer.Bank {

  protected lazy val names: Map[Byte, String] = Map(
    0x01.toByte -> "Solectron",
    0x02.toByte -> "Optosys Technologies",
    0x83.toByte -> "Buffalo (Formerly Melco)",
    0x04.toByte -> "TriMedia Technologies",
    0x85.toByte -> "Cyan Technologies",
    0x86.toByte -> "Global Locate",
    0x07.toByte -> "Optillion",
    0x08.toByte -> "TeragoCommunications",
    0x89.toByte -> "Ikanos Communications",
    0x8A.toByte -> "Princeton Technology",
    0x0B.toByte -> "Nanya Technology",
    0x8C.toByte -> "Elite Flash Storage",
    0x0D.toByte -> "Mysticom",
    0x0E.toByte -> "LightSand Communications",
    0x8F.toByte -> "ATI Technologies",
    0x10.toByte -> "Agere Systems",
    0x91.toByte -> "NeoMagic",
    0x92.toByte -> "AuroraNetics",
    0x13.toByte -> "Golden Empire",
    0x94.toByte -> "Mushkin",
    0x15.toByte -> "Tioga Technologies",
    0x16.toByte -> "Netlist",
    0x97.toByte -> "TeraLogic",
    0x98.toByte -> "Cicada Semiconductor",
    0x19.toByte -> "Centon Electronics",
    0x1A.toByte -> "Tyco Electronics",
    0x9B.toByte -> "Magis Works",
    0x1C.toByte -> "Zettacom",
    0x9D.toByte -> "Cogency Semiconductor",
    0x9E.toByte -> "Chipcon AS",
    0x1F.toByte -> "Aspex Technology",
    0x20.toByte -> "F5 Networks",
    0xA1.toByte -> "Programmable Silicon Solutions",
    0xA2.toByte -> "ChipWrights",
    0x23.toByte -> "Acorn Networks",
    0xA4.toByte -> "Quicklogic",
    0x25.toByte -> "Kingmax Semiconductor",
    0x26.toByte -> "BOPS",
    0xA7.toByte -> "Flasys",
    0xA8.toByte -> "BitBlitz Communications",
    0x29.toByte -> "eMemory Technology",
    0x2A.toByte -> "Procket Networks",
    0xAB.toByte -> "Purple Ray",
    0x2C.toByte -> "Trebia Networks",
    0xAD.toByte -> "Delta Electronics",
    0xAE.toByte -> "Onex Communications",
    0x2F.toByte -> "Ample Communications",
    0xB0.toByte -> "Memory Experts Intl",
    0x31.toByte -> "Astute Networks",
    0x32.toByte -> "Azanda Network Devices",
    0xB3.toByte -> "Dibcom",
    0x34.toByte -> "Tekmos",
    0xB5.toByte -> "API NetWorks",
    0xB6.toByte -> "Bay Microsystems",
    0x37.toByte -> "Firecron Ltd",
    0x38.toByte -> "Resonext Communications",
    0xB9.toByte -> "Tachys Technologies",
    0xBA.toByte -> "Equator Technology",
    0x3B.toByte -> "Concept Computer",
    0xBC.toByte -> "SILCOM",
    0x3D.toByte -> "3Dlabs",
    0x3E.toByte -> "c’t Magazine",
    0xBF.toByte -> "Sanera Systems",
    0x40.toByte -> "Silicon Packets",
    0xC1.toByte -> "Viasystems Group",
    0xC2.toByte -> "Simtek",
    0x43.toByte -> "Semicon Devices Singapore",
    0xC4.toByte -> "Satron Handelsges",
    0x45.toByte -> "Improv Systems",
    0x46.toByte -> "INDUSYS GmbH",
    0xC7.toByte -> "Corrent",
    0xC8.toByte -> "Infrant Technologies",
    0x49.toByte -> "Ritek Corp",
    0x4A.toByte -> "empowerTel Networks",
    0xCB.toByte -> "Hypertec",
    0x4C.toByte -> "Cavium Networks",
    0xCD.toByte -> "PLX Technology",
    0xCE.toByte -> "Massana Design",
    0x4F.toByte -> "Intrinsity",
    0xD0.toByte -> "Valence Semiconductor",
    0x51.toByte -> "Terawave Communications",
    0x52.toByte -> "IceFyre Semiconductor",
    0xD3.toByte -> "Primarion",
    0x54.toByte -> "Picochip Designs Ltd",
    0xD5.toByte -> "Silverback Systems",
    0xD6.toByte -> "Jade Star Technologies",
    0x57.toByte -> "Pijnenburg Securealink",
    0x58.toByte -> "takeMS - Ultron AG",
    0xD9.toByte -> "Cambridge Silicon Radio",
    0xDA.toByte -> "Swissbit",
    0x5B.toByte -> "Nazomi Communications",
    0xDC.toByte -> "eWave System",
    0x5D.toByte -> "Rockwell Collins",
    0x5E.toByte -> "Picocel Co. Ltd. (Paion)",
    0xDF.toByte -> "Alphamosaic Ltd",
    0xE0.toByte -> "Sandburst",
    0x61.toByte -> "SiCon Video",
    0x62.toByte -> "NanoAmp Solutions",
    0xE3.toByte -> "Ericsson Technology",
    0x64.toByte -> "PrairieComm",
    0xE5.toByte -> "Mitac International",
    0xE6.toByte -> "Layer N Networks",
    0x67.toByte -> "MtekVision (Atsana)",
    0x68.toByte -> "Allegro Networks",
    0xE9.toByte -> "Marvell Semiconductors",
    0xEA.toByte -> "Netergy Microelectronic",
    0x6B.toByte -> "NVIDIA",
    0xEC.toByte -> "Internet Machines",
    0x6D.toByte -> "Memorysolution GmbH",
    0x6E.toByte -> "Litchfield Communication",
    0xEF.toByte -> "Accton Technology",
    0x70.toByte -> "Teradiant Networks",
    0xF1.toByte -> "Scaleo Chip",
    0xF2.toByte -> "Cortina Systems",
    0x73.toByte -> "RAM Components",
    0xF4.toByte -> "Raqia Networks",
    0x75.toByte -> "ClearSpeed",
    0x76.toByte -> "Matsushita Battery",
    0xF7.toByte -> "Xelerated",
    0xF8.toByte -> "SimpleTech",
    0x79.toByte -> "Utron Technology",
    0x7A.toByte -> "Astec International",
    0xFB.toByte -> "AVM gmbH",
    0x7C.toByte -> "Redux Communications",
    0xFD.toByte -> "Dot Hill Systems",
    0xFE.toByte -> "TeraChip"
  )
}
