package com.cyclone.ipmi.sdr.jedec

object Bank06 extends Manufacturer.Bank {

  protected lazy val names: Map[Byte, String] = Map(
    0x01.toByte -> "Networks",
    0x02.toByte -> "Patriot Memory (PDP Systems)",
    0x83.toByte -> "U-Chip Technology Corp.",
    0x04.toByte -> "Silicon Optix",
    0x85.toByte -> "Greenfield Networks",
    0x86.toByte -> "CompuRAM GmbH",
    0x07.toByte -> "Stargen, Inc.",
    0x08.toByte -> "NetCell Corporation",
    0x89.toByte -> "Excalibrus Technologies Ltd",
    0x8A.toByte -> "SCM Microsystems",
    0x0B.toByte -> "Xsigo Systems, Inc.",
    0x8C.toByte -> "",
    0x0D.toByte -> "Tier 1 Multichip Solutions",
    0x0E.toByte -> "CWRL Labs",
    0x8F.toByte -> "Teradici",
    0x10.toByte -> "Gigaram, Inc.",
    0x91.toByte -> "g2 Microsystems",
    0x92.toByte -> "PowerFlash Semiconductor",
    0x13.toByte -> "P.A. Semi, Inc.",
    0x94.toByte -> "NovaTech Solutions, S.A.",
    0x15.toByte -> "c2 Microsystems, Inc.",
    0x16.toByte -> "Level5 Networks",
    0x97.toByte -> "COS Memory AG",
    0x98.toByte -> "Innovasic Semiconductor",
    0x19.toByte -> "02IC Co. Ltd",
    0x1A.toByte -> "Tabula, Inc.",
    0x9B.toByte -> "Crucial Technology",
    0x1C.toByte -> "Chelsio Communications",
    0x9D.toByte -> "Solarflare Communications",
    0x9E.toByte -> "Xambala Inc.",
    0x1F.toByte -> "EADS Astrium",
    0x20.toByte -> "Terra Semiconductor, Inc.",
    0xA1.toByte -> "Imaging Works, Inc.",
    0xA2.toByte -> "Astute Networks, Inc.",
    0x23.toByte -> "Tzero",
    0xA4.toByte -> "Emulex",
    0x25.toByte -> "Power-One",
    0x26.toByte -> "Pulse~LINK Inc.",
    0xA7.toByte -> "Hon Hai Precision Industry",
    0xA8.toByte -> "White Rock Networks Inc.",
    0x29.toByte -> "Telegent Systems USA, Inc.",
    0x2A.toByte -> "Atrua Technologies, Inc.",
    0xAB.toByte -> "Acbel Polytech Inc.",
    0x2C.toByte -> "eRide Inc.",
    0xAD.toByte -> "ULi Electronics Inc.",
    0xAE.toByte -> "Magnum Semiconductor Inc.",
    0x2F.toByte -> "neoOne Technology, Inc.",
    0xB0.toByte -> "Connex Technology, Inc.",
    0x31.toByte -> "Stream Processors, Inc.",
    0x32.toByte -> "Focus Enhancements",
    0xB3.toByte -> "Telecis Wireless, Inc.",
    0x34.toByte -> "uNav Microelectronics",
    0xB5.toByte -> "Tarari, Inc.",
    0xB6.toByte -> "Ambric, Inc.",
    0x37.toByte -> "Newport Media, Inc.",
    0x38.toByte -> "VMTS",
    0xB9.toByte -> "Enuclia Semiconductor, Inc.",
    0xBA.toByte -> "Virtium Technology Inc.",
    0x3B.toByte -> "Solid State System Co., Ltd.",
    0xBC.toByte -> "Kian Tech LLC",
    0x3D.toByte -> "Artimi",
    0x3E.toByte -> "Power Quotient International",
    0xBF.toByte -> "Avago Technologies",
    0x40.toByte -> "ADTechnology",
    0xC1.toByte -> "Sigma Designs",
    0xC2.toByte -> "SiCortex, Inc.",
    0x43.toByte -> "Ventura Technology Group",
    0xC4.toByte -> "eASIC",
    0x45.toByte -> "M.H.S. SAS",
    0x46.toByte -> "Micro Star International",
    0xC7.toByte -> "Rapport Inc.",
    0xC8.toByte -> "Makway International",
    0x49.toByte -> "Broad Reach Engineering Co.",
    0x4A.toByte -> "Semiconductor Mfg Intl Corp",
    0xCB.toByte -> "SiConnect",
    0x4C.toByte -> "FCI USA Inc.",
    0xCD.toByte -> "Validity Sensors",
    0xCE.toByte -> "Coney Technology Co. Ltd.",
    0x4F.toByte -> "Spans Logic",
    0xD0.toByte -> "Neterion Inc.",
    0x51.toByte -> "Qimonda",
    0x52.toByte -> "New Japan Radio Co. Ltd.",
    0xD3.toByte -> "Velogix",
    0x54.toByte -> "Montalvo Systems",
    0xD5.toByte -> "iVivity Inc.",
    0xD6.toByte -> "Walton Chaintech",
    0x57.toByte -> "AENEON",
    0x58.toByte -> "Lorom Industrial Co. Ltd.",
    0xD9.toByte -> "Radiospire Networks",
    0xDA.toByte -> "Sensio Technologies, Inc.",
    0x5B.toByte -> "Nethra Imaging",
    0xDC.toByte -> "Hexon Technology Pte Ltd",
    0x5D.toByte -> "CompuStocx (CSX)",
    0x5E.toByte -> "Methode Electronics, Inc.",
    0xDF.toByte -> "Connect One Ltd.",
    0xE0.toByte -> "Opulan Technologies",
    0x61.toByte -> "Septentrio NV",
    0x62.toByte -> "Goldenmars Technology Inc.",
    0xE3.toByte -> "Kreton Corporation",
    0x64.toByte -> "Cochlear Ltd.",
    0xE5.toByte -> "Altair Semiconductor",
    0xE6.toByte -> "NetEffect, Inc.",
    0x67.toByte -> "Spansion, Inc.",
    0x68.toByte -> "Taiwan Semiconductor Mfg",
    0xE9.toByte -> "Emphany Systems Inc.",
    0xEA.toByte -> "ApaceWave Technologies",
    0x6B.toByte -> "Mobilygen Corporation",
    0xEC.toByte -> "Tego",
    0x6D.toByte -> "Cswitch Corporation",
    0x6E.toByte -> "Haier (Beijing) IC Design Co.",
    0xEF.toByte -> "MetaRAM",
    0x70.toByte -> "Axel Electronics Co. Ltd.",
    0xF1.toByte -> "Tilera Corporation",
    0xF2.toByte -> "Aquantia",
    0x73.toByte -> "Vivace Semiconductor",
    0xF4.toByte -> "Redpine Signals",
    0x75.toByte -> "Octalica",
    0x76.toByte -> "InterDigital Communications",
    0xF7.toByte -> "Avant Technology",
    0xF8.toByte -> "Asrock, Inc.",
    0x79.toByte -> "Availink",
    0x7A.toByte -> "Quartics, Inc.",
    0xFB.toByte -> "Element CXI",
    0x7C.toByte -> "Innovaciones Microelectronicas",
    0xFD.toByte -> "VeriSilicon Microelectronics",
    0xFE.toByte -> "W5 Networks"
  )
}
