package com.cyclone.ipmi.sdr.jedec

// JEDEC Manufacturer lookup
// See STANDARD MANUFACTURERS IDENTIFICATION CODE at https://www.jedec.org/
// This code is based on document JEP106AT published Spe 2016

object Bank05 extends Manufacturer.Bank {

  protected lazy val names: Map[Byte, String] = Map(
    0x01.toByte -> "T-RAM Incorporated",
    0x02.toByte -> "Innovics Wireless",
    0x83.toByte -> "Teknovus",
    0x04.toByte -> "KeyEye Communications",
    0x85.toByte -> "Runcom Technologies",
    0x86.toByte -> "RedSwitch",
    0x07.toByte -> "Dotcast",
    0x08.toByte -> "Silicon Mountain Memory",
    0x89.toByte -> "Signia Technologies",
    0x8A.toByte -> "Pixim",
    0x0B.toByte -> "Galazar Networks",
    0x8C.toByte -> "White Electronic Designs",
    0x0D.toByte -> "Patriot Scientific",
    0x0E.toByte -> "Neoaxiom Corporation",
    0x8F.toByte -> "3Y Power Technology",
    0x10.toByte -> "Scaleo Chip",
    0x91.toByte -> "Potentia Power Systems",
    0x92.toByte -> "C-guys Incorporated",
    0x13.toByte -> "Digital Communications Technology Incorporated",
    0x94.toByte -> "Silicon-Based Technology",
    0x15.toByte -> "Fulcrum Microsystems",
    0x16.toByte -> "Positivo Informatica Ltd",
    0x97.toByte -> "XIOtech Corporation",
    0x98.toByte -> "PortalPlayer",
    0x19.toByte -> "Zhiying Software",
    0x1A.toByte -> "ParkerVision, Inc.",
    0x9B.toByte -> "Phonex Broadband",
    0x1C.toByte -> "Skyworks Solutions",
    0x9D.toByte -> "Entropic Communications",
    0x9E.toByte -> "I’M Intelligent Memory Ltd.",
    0x1F.toByte -> "Zensys A/S",
    0x20.toByte -> "Legend Silicon Corp.",
    0xA1.toByte -> "Sci-worx GmbH",
    0xA2.toByte -> "SMSC (Standard Microsystems)",
    0x23.toByte -> "Renesas Electronics",
    0xA4.toByte -> "Raza Microelectronics",
    0x25.toByte -> "Phyworks",
    0x26.toByte -> "MediaTek",
    0xA7.toByte -> "Non-cents Productions",
    0xA8.toByte -> "US Modular",
    0x29.toByte -> "Wintegra Ltd.",
    0x2A.toByte -> "Mathstar",
    0xAB.toByte -> "StarCore",
    0x2C.toByte -> "Oplus Technologies",
    0xAD.toByte -> "Mindspeed",
    0xAE.toByte -> "Just Young Computer",
    0x2F.toByte -> "Radia Communications",
    0xB0.toByte -> "OCZ",
    0x31.toByte -> "Emuzed",
    0x32.toByte -> "LOGIC Devices",
    0xB3.toByte -> "Inphi Corporation",
    0x34.toByte -> "Quake Technologies",
    0xB5.toByte -> "Vixel",
    0xB6.toByte -> "SolusTek",
    0x37.toByte -> "Kongsberg Maritime",
    0x38.toByte -> "Faraday Technology",
    0xB9.toByte -> "Altium Ltd.",
    0xBA.toByte -> "Insyte",
    0x3B.toByte -> "ARM Ltd.",
    0xBC.toByte -> "DigiVision",
    0x3D.toByte -> "Vativ Technologies",
    0x3E.toByte -> "Endicott Interconnect Technologies",
    0xBF.toByte -> "Pericom",
    0x40.toByte -> "Bandspeed",
    0xC1.toByte -> "LeWiz Communications",
    0xC2.toByte -> "CPU Technology",
    0x43.toByte -> "Ramaxel Technology",
    0xC4.toByte -> "DSP Group",
    0x45.toByte -> "Axis Communications",
    0x46.toByte -> "Legacy Electronics",
    0xC7.toByte -> "Chrontel",
    0xC8.toByte -> "Powerchip Semiconductor",
    0x49.toByte -> "MobilEye Technologies",
    0x4A.toByte -> "Excel Semiconductor",
    0xCB.toByte -> "A-DATA Technology",
    0x4C.toByte -> "VirtualDigm",
    0xCD.toByte -> "G Skill Intl",
    0xCE.toByte -> "Quanta Computer",
    0x4F.toByte -> "Yield Microelectronics",
    0xD0.toByte -> "Afa Technologies",
    0x51.toByte -> "KINGBOX Technology Co. Ltd.",
    0x52.toByte -> "Ceva",
    0xD3.toByte -> "iStor Networks",
    0x54.toByte -> "Advance Modules",
    0xD5.toByte -> "Microsoft",
    0xD6.toByte -> "Open-Silicon",
    0x57.toByte -> "Goal Semiconductor",
    0x58.toByte -> "ARC International",
    0xD9.toByte -> "Simmtec",
    0xDA.toByte -> "Metanoia",
    0x5B.toByte -> "Key Stream",
    0xDC.toByte -> "Lowrance Electronics",
    0x5D.toByte -> "Adimos",
    0x5E.toByte -> "SiGe Semiconductor",
    0xDF.toByte -> "Fodus Communications",
    0xE0.toByte -> "Credence Systems Corp.",
    0x61.toByte -> "Genesis Microchip Inc.",
    0x62.toByte -> "Vihana, Inc.",
    0xE3.toByte -> "WIS Technologies",
    0x64.toByte -> "GateChange Technologies",
    0xE5.toByte -> "High Density Devices AS",
    0xE6.toByte -> "Synopsys",
    0x67.toByte -> "Gigaram",
    0x68.toByte -> "Enigma Semiconductor Inc.",
    0xE9.toByte -> "Century Micro Inc.",
    0xEA.toByte -> "Icera Semiconductor",
    0x6B.toByte -> "Mediaworks Integrated Systems",
    0xEC.toByte -> "O’Neil Product Development",
    0x6D.toByte -> "Supreme Top Technology Ltd.",
    0x6E.toByte -> "MicroDisplay Corporation",
    0xEF.toByte -> "Team Group Inc.",
    0x70.toByte -> "Sinett Corporation",
    0xF1.toByte -> "Toshiba Corporation",
    0xF2.toByte -> "Tensilica",
    0x73.toByte -> "SiRF Technology",
    0xF4.toByte -> "Bacoc Inc.",
    0x75.toByte -> "SMaL Camera Technologies",
    0x76.toByte -> "Thomson SC",
    0xF7.toByte -> "Airgo Networks",
    0xF8.toByte -> "Wisair Ltd.",
    0x79.toByte -> "SigmaTel",
    0x7A.toByte -> "Arkados",
    0xFB.toByte -> "Compete IT gmbH Co. KG",
    0x7C.toByte -> "Eudar Technology Inc.",
    0xFD.toByte -> "Focus Enhancements",
    0xFE.toByte -> "Xyratex"
  )
}
