package com.cyclone.ipmi.sdr.jedec

object Bank02 extends Manufacturer.Bank {

  protected lazy val names: Map[Byte, String] = Map(
    0x01.toByte -> "Cirrus Logic",
    0x02.toByte -> "National Instruments",
    0x83.toByte -> "ILC Data Device",
    0x04.toByte -> "Alcatel Mietec",
    0x85.toByte -> "Micro Linear",
    0x86.toByte -> "Univ. of NC",
    0x07.toByte -> "JTAG Technologies",
    0x08.toByte -> "BAE Systems (Loral)",
    0x89.toByte -> "Nchip",
    0x8A.toByte -> "Galileo Tech",
    0x0B.toByte -> "Bestlink Systems",
    0x8C.toByte -> "Graychip",
    0x0D.toByte -> "GENNUM",
    0x0E.toByte -> "VideoLogic",
    0x8F.toByte -> "Robert Bosch",
    0x10.toByte -> "Chip Express",
    0x91.toByte -> "DATARAM",
    0x92.toByte -> "United Microelectronics Corp.",
    0x13.toByte -> "TCSI",
    0x94.toByte -> "Smart Modular",
    0x15.toByte -> "Hughes Aircraft",
    0x16.toByte -> "Lanstar Semiconductor",
    0x97.toByte -> "Qlogic",
    0x98.toByte -> "Kingston",
    0x19.toByte -> "Music Semi",
    0x1A.toByte -> "Ericsson Components",
    0x9B.toByte -> "SpaSE",
    0x1C.toByte -> "Eon Silicon Devices",
    0x9D.toByte -> "Integrated Silicon Solution (ISSI)",
    0x9E.toByte -> "DoD",
    0x1F.toByte -> "Integ. Memories Tech.",
    0x20.toByte -> "Corollary Inc.",
    0xA1.toByte -> "Dallas Semiconductor",
    0xA2.toByte -> "Omnivision",
    0x23.toByte -> "EIV(Switzerland)",
    0xA4.toByte -> "Novatel Wireless",
    0x25.toByte -> "Zarlink (Mitel)",
    0x26.toByte -> "Clearpoint",
    0xA7.toByte -> "Cabletron",
    0xA8.toByte -> "STEC (Silicon Tech)",
    0x29.toByte -> "Vanguard",
    0x2A.toByte -> "Hagiwara Sys-Com",
    0xAB.toByte -> "Vantis",
    0x2C.toByte -> "Celestica",
    0xAD.toByte -> "Century",
    0xAE.toByte -> "Hal Computers",
    0x2F.toByte -> "Rohm Company Ltd.",
    0xB0.toByte -> "Juniper Networks",
    0x31.toByte -> "Libit Signal Processing",
    0x32.toByte -> "Mushkin Enhanced Memory",
    0xB3.toByte -> "Tundra Semiconductor",
    0x34.toByte -> "Adaptec Inc.",
    0xB5.toByte -> "LightSpeed Semi.",
    0xB6.toByte -> "ZSP Corp.",
    0x37.toByte -> "AMIC Technology",
    0x38.toByte -> "Adobe Systems",
    0xB9.toByte -> "Dynachip",
    0xBA.toByte -> "PNY Technologies, Inc.",
    0x3B.toByte -> "Newport Digital",
    0xBC.toByte -> "MMC Networks",
    0x3D.toByte -> "T Square",
    0x3E.toByte -> "Seiko Epson",
    0xBF.toByte -> "Broadcom",
    0x40.toByte -> "Viking Components",
    0xC1.toByte -> "V3 Semiconductor",
    0xC2.toByte -> "Flextronics (Orbit Semiconductor)",
    0x43.toByte -> "Suwa Electronics",
    0xC4.toByte -> "Transmeta",
    0x45.toByte -> "Micron CMS",
    0x46.toByte -> "American Computer & Digital Components Inc.",
    0xC7.toByte -> "Enhance 3000 Inc.",
    0xC8.toByte -> "Tower Semiconductor",
    0x49.toByte -> "CPU Design",
    0x4A.toByte -> "Price Point",
    0xCB.toByte -> "Maxim Integrated Product",
    0x4C.toByte -> "Tellabs",
    0xCD.toByte -> "Centaur Technology",
    0xCE.toByte -> "Unigen Corporation",
    0x4F.toByte -> "Transcend Information",
    0xD0.toByte -> "Memory Card Technology",
    0x51.toByte -> "CKD Corporation Ltd.",
    0x52.toByte -> "Capital Instruments, Inc.",
    0xD3.toByte -> "Aica Kogyo, Ltd.",
    0x54.toByte -> "Linvex Technology",
    0xD5.toByte -> "MSC Vertriebs GmbH",
    0xD6.toByte -> "AKM Company, Ltd.",
    0x57.toByte -> "Dynamem, Inc.",
    0x58.toByte -> "NERA ASA",
    0xD9.toByte -> "GSI Technology",
    0xDA.toByte -> "Dane-Elec (C Memory)",
    0x5B.toByte -> "Acorn Computers",
    0xDC.toByte -> "Lara Technology",
    0x5D.toByte -> "Oak Technology, Inc.",
    0x5E.toByte -> "Itec Memory",
    0xDF.toByte -> "Tanisys Technology",
    0xE0.toByte -> "Truevision",
    0x61.toByte -> "Wintec Industries",
    0x62.toByte -> "Super PC Memory",
    0xE3.toByte -> "MGV Memory",
    0x64.toByte -> "Galvantech",
    0xE5.toByte -> "Gadzoox Networks",
    0xE6.toByte -> "Multi Dimensional Cons.",
    0x67.toByte -> "GateField",
    0x68.toByte -> "Integrated Memory System",
    0xE9.toByte -> "Triscend",
    0xEA.toByte -> "XaQti",
    0x6B.toByte -> "Goldenram",
    0xEC.toByte -> "Clear Logic",
    0x6D.toByte -> "Cimaron Communications",
    0x6E.toByte -> "Nippon Steel Semi. Corp.",
    0xEF.toByte -> "Advantage Memory",
    0x70.toByte -> "AMCC",
    0xF1.toByte -> "LeCroy",
    0xF2.toByte -> "Yamaha Corporation",
    0x73.toByte -> "Digital Microwave",
    0xF4.toByte -> "NetLogic Microsystems",
    0x75.toByte -> "MIMOS Semiconductor",
    0x76.toByte -> "Advanced Fibre",
    0xF7.toByte -> "BF Goodrich Data.",
    0xF8.toByte -> "Epigram",
    0x79.toByte -> "Acbel Polytech Inc.",
    0x7A.toByte -> "Apacer Technology",
    0xFB.toByte -> "Admor Memory",
    0x7C.toByte -> "FOXCONN",
    0xFD.toByte -> "Quadratics Superconductor",
    0xFE.toByte -> "3COM"
  )
}
